export const demoOffers = [
  {
    id: 'offer-urban',
    storeId: 'urban-style',
    store: 'Urban Style',
    initials: 'US',
    color: '#b72435',
    product: 'Zapatillas Urban Classic',
    detail: 'Disponible en negro, talla 42. Puedes probártelas en tienda.',
    availability: 'Disponible ahora',
    confirmed: 'Confirmado hace 2 min',
    location: 'Pabellón B · Local 208',
    floor: 'Piso 2',
    mapId: 'B-208',
    image: 'zapatillas',
  },
  {
    id: 'offer-distrito',
    storeId: 'distrito-5',
    store: 'Distrito 5',
    initials: 'D5',
    color: '#166b91',
    product: 'Street One Black',
    detail: 'Modelo urbano en negro, talla 42. Últimas unidades.',
    availability: 'Últimas 2 unidades',
    confirmed: 'Confirmado hace 4 min',
    location: 'Pabellón B · Local 214',
    floor: 'Piso 2',
    mapId: 'B-214',
    image: 'zapatillas',
  },
  {
    id: 'offer-paso',
    storeId: 'paso-firme',
    store: 'Paso Firme',
    initials: 'PF',
    color: '#9a6a19',
    product: 'Urban Flex 42',
    detail: 'Alternativa similar en negro y grafito, lista para probar.',
    availability: 'Disponible hoy',
    confirmed: 'Confirmado hace 7 min',
    location: 'Pabellón C · Local 307',
    floor: 'Piso 1',
    mapId: 'C-307',
    image: 'zapatillas',
  },
];

export const merchantLeads = [
  {
    id: 'lead-1',
    query: 'Audífonos inalámbricos con cancelación de ruido',
    category: 'Tecnología',
    customer: 'María G.',
    time: 'Hace 2 min',
    detail: 'Prefiere color negro. Los necesita hoy.',
  },
  {
    id: 'lead-2',
    query: 'Smartwatch resistente al agua',
    category: 'Tecnología',
    customer: 'Carlos R.',
    time: 'Hace 8 min',
    detail: 'Busca uno compatible con Android.',
  },
  {
    id: 'lead-3',
    query: 'Mochila para laptop de 15 pulgadas',
    category: 'Accesorios',
    customer: 'Andrea P.',
    time: 'Hace 14 min',
    detail: 'Consulta por un modelo impermeable.',
  },
];
